# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: xnet-inc-os
# description will be included in the image's metadata
description: This is an OS image for XNet Inc. developers, customized by Joshua S. Doucette.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/vauxite-main
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
      files:
        - /etc/yum.repos.d/google-chrome.repo
        - /etc/yum.repos.d/gh-cli.repo
        - /etc/yum.repos.d/google-cloud-sdk.repo
        - /etc/yum.repos.d/vscodium.repo
        - /etc/yum.repos.d/rpmfusion-free.repo
        - /etc/yum.repos.d/rpmfusion-nonfree.repo
    install:
      packages:
        - micro
        - starship
        - gnome-boxes
        - virt-manager
        - distrobox
        - google-chrome-unstable
        - git
        - gh
        - libxcrypt-compat.x86_64
        - google-cloud-cli
        - codium
        - nodejs
        - engrampa
        - system-config-printer
        - gutenprint
        - evince
        - kitty
        - NetworkManager-tui
        - gparted
        - cockpit
        - cockpit-bridge
        - cockpit-doc
        - cockpit-kdump
        - cockpit-networkmanager
        - cockpit-packagekit
        - cockpit-selinux
        - cockpit-sosreport
        - cockpit-storaged
        - cockpit-system
        - cockpit-machines
        - cockpit-podman
        - cockpit-ostree
        - setroubleshoot-server
        - setools-console
        - selinux-policy-devel
        - policycoreutils-devel
        - mcstrans
        - dejavu-sans-fonts
        - dejavu-serif-fonts
        - dnf-plugins-core
        - tigervnc
        - wireshark
        - libreoffice
        - vlc
        - strace
        - ltrace
        - pam-devel

  - type: script
    snippets:
      - |
        #!/usr/bin/env bash
        set -oue pipefail

        # Install antigravity
        pip install antigravity

        # Install Gemini CLI
        npm install -g @google/gemini-cli

        # Enable CUPS service (do not start)
        systemctl enable cups

        # Enable Cockpit socket (do not start)
        systemctl enable cockpit.socket

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.gnome.Loupe
          - com.rustdesk.RustDesk
      - scope: user