---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: xnet-inc-os
# description will be included in the image's metadata
description: This is an OS image for XNet Inc. developers, customized by Joshua S. Doucette.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
      files:
        - /etc/yum.repos.d/google-chrome.repo
        - /etc/yum.repos.d/gh-cli.repo
        - /etc/yum.repos.d/google-cloud-sdk.repo
        - /etc/yum.repos.d/vscodium.repo
        - /etc/yum.repos.d/rustdesk.repo
    install:
      packages:
        - micro
        - starship
        - nano
        - gnome-boxes
        - virt-manager
        - distrobox
        - google-chrome-unstable
        - git
        - gh
        - libxcrypt-compat.x86_64
        - google-cloud-cli
        - codium
        - python3
        - python3-pip
        - nodejs
        - '@xfce-desktop-environment'
        - lightdm
        - lightdm-gtk
        - engrampa
        - xfce4-clipman-plugin
        - cups
        - cups-filters
        - system-config-printer
        - gutenprint
        - rpmfusion-free-release
        - rpmfusion-nonfree-release
        - akmod-nvidia
        - xorg-x11-drv-nvidia-cuda
        - evince
        - kitty
        - NetworkManager-tui
        - wireguard-tools
        - gparted
        - podman
        - podman-docker
        - podman-machine
        - podman-remote
        - podmansh
        - slirp4netns
        - cockpit
        - cockpit-bridge
        - cockpit-doc
        - cockpit-kdump
        - cockpit-networkmanager
        - cockpit-packagekit
        - cockpit-selinux
        - cockpit-sosreport
        - cockpit-storaged
        - cockpit-system
        - cockpit-machines
        - cockpit-podman
        - cockpit-ostree
        - setroubleshoot-server
        - setools-console
        - selinux-policy-devel
        - policycoreutils-devel
        - mcstrans
        - selinux-basics
        - net-tools
        - traceroute
        - nmap-ncat
        - bind-utils
        - gnome-online-accounts
        - gnome-keyring
        - make
        - gcc
        - autoconf
        - automake
        - openssh-clients
        - xfce4-screenshooter
        - xfce4-taskmanager
        - google-noto-color-emoji-fonts
        - dejavu-sans-fonts
        - dejavu-serif-fonts
        - dejavu-mono-fonts
        - zip
        - unzip
        - rsync
        - htop
        - cryptsetup
        - lvm2
        - e2fsprogs
        - xfsprogs
        - thunar-archive-plugin
        - dnf-plugins-core
        - rustdesk
        - sane-backends
        - simple-scan
        - tigervnc
        - wireshark
        - htttrack
        - libreoffice
        - vlc
        - nmap
        - masscan
        - hping3
        - nikto
        - sqlmap
        - dirb
        - gobuster
        - john
        - hashcat
        - crunch
        - binwalk
        - foremost
        - testdisk
        - radare2
        - aircrack-ng
        - kismet
        - proxychains-ng
        - tor
        - strace
        - ltrace
        - wipe
        - scalpel
        - extundelete
        - gstreamer1-plugins-ugly
        - gstreamer1-plugins-bad
        - ffmpeg
        - go
        - rust
        - java-latest-openjdk
        - php
        - ruby
    remove:
      packages:
        # Firefox related packages were removed earlier. This section remains as a placeholder.

  - type: script
    snippets:
      - |
        #!/usr/bin/env bash
        set -oue pipefail

        # Install antigravity
        pip install antigravity

        # Install Gemini CLI
        npm install -g @google/gemini-cli

        # Disable GDM and enable LightDM
        systemctl disable gdm.service || true # Use || true in case GDM isn't active
        systemctl enable lightdm.service

        # Set XFCE as the default session in LightDM
        mkdir -p /etc/lightdm/lightdm.conf.d
        echo "[Seat:*]" > /etc/lightdm/lightdm.conf.d/50-xnet-inc-os.conf
        echo "user-session=xfce" >> /etc/lightdm/lightdm.conf.d/50-xnet-inc-os.conf

        # Enable and start CUPS service
        systemctl enable cups || true
        systemctl start cups || true

        # Enable and start Cockpit socket
        systemctl enable --now cockpit.socket || true

        # Configure firewall
        if command -v firewall-cmd &> /dev/null
        then
            # CUPS
            firewall-cmd --add-service=ipp --permanent || true
            firewall-cmd --add-service=ipp-client --permanent || true
            
            # Cockpit
            firewall-cmd --add-service=cockpit --permanent || true
            
            # RustDesk
            firewall-cmd --permanent --add-port=21114-21119/tcp || true
            firewall-cmd --permanent --add-port=21116/udp || true
            
            firewall-cmd --reload || true
        fi

  - type: default-flatpaks
